# Generated by Django 5.1.4 on 2025-01-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_dadosmedico_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmedico',
            name='cidade',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
